package utils

const (
	MONGODB_USER_DB = "MONGODB_USER_DB"
	MONGODB_PRODUCT_DB = "MONGODB_PRODUCT_DB"
	MONGODB_ADDRESS_DB = "MONGODB_ADDRESS_DB"
	MONGODB_ALLOWED_CITIES_DB = "MONGODB_ALLOWED_CITIES_DB"

)